#!/bin/bash

# Install the JupyterLab dask-labextension
jupyter labextension install dask-labextension@2.0.0 || true
jupyter labextension install @jupyter-widgets/jupyterlab-manager || true
jupyter labextension install @bokeh/jupyter_bokeh || true
