#!/bin/bash

# Install the JupyterLab dask-labextension
jupyter labextension install dask-labextension@2.0.0
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @bokeh/jupyter_bokeh
